/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bed97a4e-5687-4717-9b89-4a95ee8033e7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_p3Awy5anT",
    "aws_user_pools_web_client_id": "dcokkhg2dbi283orjukhsb2pt",
    "oauth": {}
};


export default awsmobile;
